<?php

declare(strict_types=1);

return [
    'version' => '2026-04-28',
    'categories' => [
        'histoire-industrie' => [
            'label' => [
                'fr' => 'Histoire et industrie',
                'en' => 'History and industry',
                'de' => 'Geschichte und Industrie',
            ],
            'seo' => 'index',
            'subcategories' => ['origines-chronologie', 'industrie-longbridge'],
        ],
        'modeles-vehicules' => [
            'label' => [
                'fr' => 'Modèles et véhicules',
                'en' => 'Models and vehicles',
                'de' => 'Modelle und Fahrzeuge',
            ],
            'seo' => 'index',
            'subcategories' => ['berlines-populaires', 'sport-roadsters'],
        ],
        'technique-restauration' => [
            'label' => [
                'fr' => 'Technique et restauration',
                'en' => 'Technical and restoration',
                'de' => 'Technik und Restaurierung',
            ],
            'seo' => 'index',
            'subcategories' => ['mecanique-entretien', 'restauration-pieces'],
        ],
        'usage-collection' => [
            'label' => [
                'fr' => 'Usage et collection',
                'en' => 'Use and collecting',
                'de' => 'Nutzung und Sammlung',
            ],
            'seo' => 'index',
            'subcategories' => ['conduite-balades', 'achat-cote'],
        ],
    ],
    'subcategories' => [
        'origines-chronologie' => [
            'category' => 'histoire-industrie',
            'label' => [
                'fr' => 'Origines et chronologie',
                'en' => 'Origins and timeline',
                'de' => 'Ursprünge und Chronologie',
            ],
            'seo' => 'index',
        ],
        'industrie-longbridge' => [
            'category' => 'histoire-industrie',
            'label' => [
                'fr' => 'Industrie et Longbridge',
                'en' => 'Industry and Longbridge',
                'de' => 'Industrie und Longbridge',
            ],
            'seo' => 'index',
        ],
        'berlines-populaires' => [
            'category' => 'modeles-vehicules',
            'label' => [
                'fr' => 'Berlines et populaires',
                'en' => 'Saloons and popular cars',
                'de' => 'Limousinen und beliebte Fahrzeuge',
            ],
            'seo' => 'index',
        ],
        'sport-roadsters' => [
            'category' => 'modeles-vehicules',
            'label' => [
                'fr' => 'Sport et roadsters',
                'en' => 'Sport and roadsters',
                'de' => 'Sport und Roadster',
            ],
            'seo' => 'index',
        ],
        'mecanique-entretien' => [
            'category' => 'technique-restauration',
            'label' => [
                'fr' => 'Mécanique et entretien',
                'en' => 'Mechanics and maintenance',
                'de' => 'Mechanik und Wartung',
            ],
            'seo' => 'index',
        ],
        'restauration-pieces' => [
            'category' => 'technique-restauration',
            'label' => [
                'fr' => 'Restauration et pièces',
                'en' => 'Restoration and parts',
                'de' => 'Restaurierung und Teile',
            ],
            'seo' => 'index',
        ],
        'conduite-balades' => [
            'category' => 'usage-collection',
            'label' => [
                'fr' => 'Conduite et balades',
                'en' => 'Driving and outings',
                'de' => 'Fahren und Ausfahrten',
            ],
            'seo' => 'index',
        ],
        'achat-cote' => [
            'category' => 'usage-collection',
            'label' => [
                'fr' => 'Achat et cote',
                'en' => 'Buying and values',
                'de' => 'Kauf und Marktwerte',
            ],
            'seo' => 'index',
        ],
    ],
    'tags' => [
        'austin' => ['fr' => 'Austin', 'en' => 'Austin', 'de' => 'Austin'],
        'longbridge' => ['fr' => 'Longbridge', 'en' => 'Longbridge', 'de' => 'Longbridge'],
        'bmc' => ['fr' => 'BMC', 'en' => 'BMC', 'de' => 'BMC'],
        'british-leyland' => ['fr' => 'British Leyland', 'en' => 'British Leyland', 'de' => 'British Leyland'],
        'austin-seven' => ['fr' => 'Austin Seven', 'en' => 'Austin Seven', 'de' => 'Austin Seven'],
        'austin-a30' => ['fr' => 'Austin A30', 'en' => 'Austin A30', 'de' => 'Austin A30'],
        'austin-a40-farina' => ['fr' => 'Austin A40 Farina', 'en' => 'Austin A40 Farina', 'de' => 'Austin A40 Farina'],
        'austin-cambridge' => ['fr' => 'Austin Cambridge', 'en' => 'Austin Cambridge', 'de' => 'Austin Cambridge'],
        'austin-healey' => ['fr' => 'Austin-Healey', 'en' => 'Austin-Healey', 'de' => 'Austin-Healey'],
        'mini-austin' => ['fr' => 'Mini Austin', 'en' => 'Austin Mini', 'de' => 'Austin Mini'],
        'herbert-austin' => ['fr' => 'Herbert Austin', 'en' => 'Herbert Austin', 'de' => 'Herbert Austin'],
        'pininfarina' => ['fr' => 'Pininfarina', 'en' => 'Pininfarina', 'de' => 'Pininfarina'],
        'morris' => ['fr' => 'Morris', 'en' => 'Morris', 'de' => 'Morris'],
        'mg' => ['fr' => 'MG', 'en' => 'MG', 'de' => 'MG'],
        'birmingham' => ['fr' => 'Birmingham', 'en' => 'Birmingham', 'de' => 'Birmingham'],
        'roadster-anglais' => ['fr' => 'roadster anglais', 'en' => 'British roadster', 'de' => 'britischer Roadster'],
        'voiture-anglaise' => ['fr' => 'voiture anglaise', 'en' => 'British car', 'de' => 'britisches Auto'],
        'voiture-ancienne' => ['fr' => 'voiture ancienne', 'en' => 'classic car', 'de' => 'Oldtimer'],
        'avant-guerre' => ['fr' => 'avant-guerre', 'en' => 'pre-war', 'de' => 'Vorkriegszeit'],
        'conduite-ancienne' => ['fr' => 'conduite ancienne', 'en' => 'classic driving', 'de' => 'Oldtimerfahren'],
        'saint-tropez' => ['fr' => 'Saint-Tropez', 'en' => 'Saint-Tropez', 'de' => 'Saint-Tropez'],
        'restauration' => ['fr' => 'restauration', 'en' => 'restoration', 'de' => 'Restaurierung'],
        'pieces-detachees' => ['fr' => 'pièces détachées', 'en' => 'spare parts', 'de' => 'Ersatzteile'],
        'mecanique-anglaise' => ['fr' => 'mécanique anglaise', 'en' => 'British mechanics', 'de' => 'britische Mechanik'],
        'moteur-a-series' => ['fr' => 'moteur A-Series', 'en' => 'A-Series engine', 'de' => 'A-Series-Motor'],
        'technique-automobile' => ['fr' => 'technique automobile', 'en' => 'automotive engineering', 'de' => 'Fahrzeugtechnik'],
        'industrie-britannique' => ['fr' => 'industrie britannique', 'en' => 'British industry', 'de' => 'britische Industrie'],
        'achat-collection' => ['fr' => 'achat collection', 'en' => 'collector purchase', 'de' => 'Sammlerkauf'],
        'prix-cote' => ['fr' => 'prix et cote', 'en' => 'prices and values', 'de' => 'Preise und Marktwerte'],
        'austin-rover' => ['fr' => 'Austin Rover', 'en' => 'Austin Rover', 'de' => 'Austin Rover'],
    ],
    'seo' => [
        'tag_default' => 'noindex',
    ],
    'aliases' => [
        'categories' => [
            'histoire de marque' => 'histoire-industrie',
            'markengeschichte' => 'histoire-industrie',
            'brand history' => 'histoire-industrie',
            'industrie automobile' => 'histoire-industrie',
            'modèles emblématiques' => 'modeles-vehicules',
            'modeles emblematiques' => 'modeles-vehicules',
            'technique' => 'technique-restauration',
            'guide pratique' => 'usage-collection',
            'expérience de conduite' => 'usage-collection',
            'experience de conduite' => 'usage-collection',
        ],
        'subcategories' => [
            'chronologie austin' => 'origines-chronologie',
            'industrie automobile britannique' => 'industrie-longbridge',
            'longbridge' => 'industrie-longbridge',
            'berline britannique' => 'berlines-populaires',
            'voiture populaire' => 'berlines-populaires',
            'roadster anglais' => 'sport-roadsters',
            'entretien austin' => 'mecanique-entretien',
            'mecanique anglaise' => 'mecanique-entretien',
            'mécanique anglaise' => 'mecanique-entretien',
            'restauration austin' => 'restauration-pieces',
            'pièces austin' => 'restauration-pieces',
            'pieces austin' => 'restauration-pieces',
            'balade en ancienne' => 'conduite-balades',
            'conduite ancienne' => 'conduite-balades',
            'achat voiture ancienne' => 'achat-cote',
            'cote austin' => 'achat-cote',
            'prix voiture ancienne' => 'achat-cote',
        ],
        'tags' => [
            'A30' => 'austin-a30',
            'Austin Mini' => 'mini-austin',
            'mini austin' => 'mini-austin',
            'Austin-Healey' => 'austin-healey',
            'Austin Healey' => 'austin-healey',
            'Donald Healey' => 'austin-healey',
            'Austin Rover' => 'austin-rover',
            'Austin A40 Farina' => 'austin-a40-farina',
            'Austin Cambridge' => 'austin-cambridge',
            'Austin Seven' => 'austin-seven',
            'Golfe de Saint-Tropez' => 'saint-tropez',
            'saint tropez' => 'saint-tropez',
            'St Tropez' => 'saint-tropez',
            'moteur Austin' => 'moteur-a-series',
            'OHV' => 'technique-automobile',
            'fabrication automobile' => 'technique-automobile',
            'restauration Austin' => 'restauration',
            'pièces Austin' => 'pieces-detachees',
            'pieces Austin' => 'pieces-detachees',
            'industrie automobile britannique' => 'industrie-britannique',
            'industrie britannique' => 'industrie-britannique',
            'crise industrielle' => 'industrie-britannique',
            'achat voiture ancienne' => 'achat-collection',
            'collection Austin' => 'achat-collection',
            'prix voiture ancienne' => 'prix-cote',
            'cote Austin' => 'prix-cote',
            'berline britannique' => 'austin-cambridge',
            'voiture populaire' => 'austin-seven',
            'voiture anglaise ancienne' => 'voiture-anglaise',
            'voiture d’avant-guerre' => 'avant-guerre',
            'voiture d avant guerre' => 'avant-guerre',
            'balade en ancienne' => 'conduite-ancienne',
            'auto rétro' => 'voiture-ancienne',
            'auto retro' => 'voiture-ancienne',
            'chronologie Austin' => 'austin',
            'entretien Austin' => 'mecanique-anglaise',
        ],
    ],
];
