<?php

declare(strict_types=1);

return [
    'version' => '2026-04-28-taxonomy-v2',
    'limits' => [
        'max_categories' => 4,
        'max_subcategories' => 8,
        'min_tags_per_article' => 3,
        'max_tags_per_article' => 5,
        'max_tags' => 30,
    ],
    'categories' => [
        'auto-retro' => [
            'slug' => 'auto-retro',
            'label' => [
                'fr' => 'Auto-rétro',
                'en' => 'Classic cars',
                'de' => 'Oldtimer',
            ],
            'seo' => 'index',
            'subcategories' => [
                'histoire-automobile',
                'modeles-et-versions',
                'restauration-et-entretien',
                'conduite-et-collection',
            ],
        ],
        'territoire' => [
            'slug' => 'territoire',
            'label' => [
                'fr' => 'Territoire',
                'en' => 'Region',
                'de' => 'Region',
            ],
            'seo' => 'index',
            'subcategories' => [
                'golfe-saint-tropez',
                'villages-et-balades',
            ],
        ],
        'vie-locale' => [
            'slug' => 'vie-locale',
            'label' => [
                'fr' => 'Vie locale',
                'en' => 'Local life',
                'de' => 'Lokales Leben',
            ],
            'seo' => 'index',
            'subcategories' => [
                'evenements-et-animations',
            ],
        ],
        'patrimoine' => [
            'slug' => 'patrimoine',
            'label' => [
                'fr' => 'Patrimoine',
                'en' => 'Heritage',
                'de' => 'Kulturerbe',
            ],
            'seo' => 'index',
            'subcategories' => [
                'lieux-et-memoire',
            ],
        ],
    ],
    'subcategories' => [
        'histoire-automobile' => [
            'slug' => 'histoire-automobile',
            'category' => 'auto-retro',
            'label' => [
                'fr' => 'Histoire automobile',
                'en' => 'Automotive history',
                'de' => 'Automobilgeschichte',
            ],
            'seo' => 'index',
        ],
        'modeles-et-versions' => [
            'slug' => 'modeles-et-versions',
            'category' => 'auto-retro',
            'label' => [
                'fr' => 'Modèles et versions',
                'en' => 'Models and versions',
                'de' => 'Modelle und Versionen',
            ],
            'seo' => 'index',
        ],
        'restauration-et-entretien' => [
            'slug' => 'restauration-et-entretien',
            'category' => 'auto-retro',
            'label' => [
                'fr' => 'Restauration et entretien',
                'en' => 'Restoration and maintenance',
                'de' => 'Restaurierung und Wartung',
            ],
            'seo' => 'index',
        ],
        'conduite-et-collection' => [
            'slug' => 'conduite-et-collection',
            'category' => 'auto-retro',
            'label' => [
                'fr' => 'Conduite et collection',
                'en' => 'Driving and collecting',
                'de' => 'Fahren und Sammeln',
            ],
            'seo' => 'index',
        ],
        'golfe-saint-tropez' => [
            'slug' => 'golfe-saint-tropez',
            'category' => 'territoire',
            'label' => [
                'fr' => 'Golfe de Saint-Tropez',
                'en' => 'Gulf of Saint-Tropez',
                'de' => 'Golf von Saint-Tropez',
            ],
            'seo' => 'index',
        ],
        'villages-et-balades' => [
            'slug' => 'villages-et-balades',
            'category' => 'territoire',
            'label' => [
                'fr' => 'Villages et balades',
                'en' => 'Villages and walks',
                'de' => 'Dörfer und Spaziergänge',
            ],
            'seo' => 'index',
        ],
        'evenements-et-animations' => [
            'slug' => 'evenements-et-animations',
            'category' => 'vie-locale',
            'label' => [
                'fr' => 'Événements et animations',
                'en' => 'Events and activities',
                'de' => 'Veranstaltungen und Aktivitäten',
            ],
            'seo' => 'index',
        ],
        'lieux-et-memoire' => [
            'slug' => 'lieux-et-memoire',
            'category' => 'patrimoine',
            'label' => [
                'fr' => 'Lieux et mémoire',
                'en' => 'Places and memory',
                'de' => 'Orte und Erinnerung',
            ],
            'seo' => 'index',
        ],
    ],
    'tags' => [
        'mini-austin' => [
            'slug' => 'mini-austin',
            'label' => ['fr' => 'Mini Austin', 'en' => 'Austin Mini', 'de' => 'Austin Mini'],
            'seo' => 'noindex',
        ],
        'austin' => [
            'slug' => 'austin',
            'label' => ['fr' => 'Austin', 'en' => 'Austin', 'de' => 'Austin'],
            'seo' => 'noindex',
        ],
        'citroen' => [
            'slug' => 'citroen',
            'label' => ['fr' => 'Citroën', 'en' => 'Citroën', 'de' => 'Citroën'],
            'seo' => 'noindex',
        ],
        'renault' => [
            'slug' => 'renault',
            'label' => ['fr' => 'Renault', 'en' => 'Renault', 'de' => 'Renault'],
            'seo' => 'noindex',
        ],
        'panhard' => [
            'slug' => 'panhard',
            'label' => ['fr' => 'Panhard', 'en' => 'Panhard', 'de' => 'Panhard'],
            'seo' => 'noindex',
        ],
        'mercedes' => [
            'slug' => 'mercedes',
            'label' => ['fr' => 'Mercedes', 'en' => 'Mercedes', 'de' => 'Mercedes'],
            'seo' => 'noindex',
        ],
        'simca' => [
            'slug' => 'simca',
            'label' => ['fr' => 'Simca', 'en' => 'Simca', 'de' => 'Simca'],
            'seo' => 'noindex',
        ],
        'twingo' => [
            'slug' => 'twingo',
            'label' => ['fr' => 'Twingo', 'en' => 'Twingo', 'de' => 'Twingo'],
            'seo' => 'noindex',
        ],
        '2cv' => [
            'slug' => '2cv',
            'label' => ['fr' => '2CV', 'en' => '2CV', 'de' => '2CV'],
            'seo' => 'noindex',
        ],
        'voiture-ancienne' => [
            'slug' => 'voiture-ancienne',
            'label' => ['fr' => 'voiture ancienne', 'en' => 'classic car', 'de' => 'Oldtimer'],
            'seo' => 'noindex',
        ],
        'voiture-anglaise' => [
            'slug' => 'voiture-anglaise',
            'label' => ['fr' => 'voiture anglaise', 'en' => 'British car', 'de' => 'britisches Auto'],
            'seo' => 'noindex',
        ],
        'restauration' => [
            'slug' => 'restauration',
            'label' => ['fr' => 'restauration', 'en' => 'restoration', 'de' => 'Restaurierung'],
            'seo' => 'noindex',
        ],
        'entretien' => [
            'slug' => 'entretien',
            'label' => ['fr' => 'entretien', 'en' => 'maintenance', 'de' => 'Wartung'],
            'seo' => 'noindex',
        ],
        'mecanique' => [
            'slug' => 'mecanique',
            'label' => ['fr' => 'mécanique', 'en' => 'mechanics', 'de' => 'Mechanik'],
            'seo' => 'noindex',
        ],
        'carrosserie' => [
            'slug' => 'carrosserie',
            'label' => ['fr' => 'carrosserie', 'en' => 'bodywork', 'de' => 'Karosserie'],
            'seo' => 'noindex',
        ],
        'histoire' => [
            'slug' => 'histoire',
            'label' => ['fr' => 'histoire', 'en' => 'history', 'de' => 'Geschichte'],
            'seo' => 'noindex',
        ],
        'modele' => [
            'slug' => 'modele',
            'label' => ['fr' => 'modèle', 'en' => 'model', 'de' => 'Modell'],
            'seo' => 'noindex',
        ],
        'version' => [
            'slug' => 'version',
            'label' => ['fr' => 'version', 'en' => 'version', 'de' => 'Version'],
            'seo' => 'noindex',
        ],
        'collection' => [
            'slug' => 'collection',
            'label' => ['fr' => 'collection', 'en' => 'collecting', 'de' => 'Sammlung'],
            'seo' => 'noindex',
        ],
        'route' => [
            'slug' => 'route',
            'label' => ['fr' => 'route', 'en' => 'road use', 'de' => 'Straße'],
            'seo' => 'noindex',
        ],
        'experience' => [
            'slug' => 'experience',
            'label' => ['fr' => 'expérience', 'en' => 'experience', 'de' => 'Erfahrung'],
            'seo' => 'noindex',
        ],
        'golfe-saint-tropez' => [
            'slug' => 'golfe-saint-tropez',
            'label' => ['fr' => 'golfe de Saint-Tropez', 'en' => 'Gulf of Saint-Tropez', 'de' => 'Golf von Saint-Tropez'],
            'seo' => 'noindex',
        ],
        'saint-tropez' => [
            'slug' => 'saint-tropez',
            'label' => ['fr' => 'Saint-Tropez', 'en' => 'Saint-Tropez', 'de' => 'Saint-Tropez'],
            'seo' => 'noindex',
        ],
        'la-garde-freinet' => [
            'slug' => 'la-garde-freinet',
            'label' => ['fr' => 'La Garde-Freinet', 'en' => 'La Garde-Freinet', 'de' => 'La Garde-Freinet'],
            'seo' => 'noindex',
        ],
        'grimaud' => [
            'slug' => 'grimaud',
            'label' => ['fr' => 'Grimaud', 'en' => 'Grimaud', 'de' => 'Grimaud'],
            'seo' => 'noindex',
        ],
        'cogolin' => [
            'slug' => 'cogolin',
            'label' => ['fr' => 'Cogolin', 'en' => 'Cogolin', 'de' => 'Cogolin'],
            'seo' => 'noindex',
        ],
        'village' => [
            'slug' => 'village',
            'label' => ['fr' => 'village', 'en' => 'village', 'de' => 'Dorf'],
            'seo' => 'noindex',
        ],
        'balade' => [
            'slug' => 'balade',
            'label' => ['fr' => 'balade', 'en' => 'walk', 'de' => 'Spaziergang'],
            'seo' => 'noindex',
        ],
        'patrimoine' => [
            'slug' => 'patrimoine',
            'label' => ['fr' => 'patrimoine', 'en' => 'heritage', 'de' => 'Kulturerbe'],
            'seo' => 'noindex',
        ],
        'evenement' => [
            'slug' => 'evenement',
            'label' => ['fr' => 'événement', 'en' => 'event', 'de' => 'Veranstaltung'],
            'seo' => 'noindex',
        ],
    ],
    'seo' => [
        'tag_default' => 'noindex',
        'tag_robots' => 'noindex,follow',
    ],
    'aliases' => [
        'categories' => [
            'histoire-industrie' => 'auto-retro',
            'histoire de marque' => 'auto-retro',
            'markengeschichte' => 'auto-retro',
            'brand history' => 'auto-retro',
            'industrie automobile' => 'auto-retro',
            'modeles-vehicules' => 'auto-retro',
            'modèles emblématiques' => 'auto-retro',
            'modeles emblematiques' => 'auto-retro',
            'technique-restauration' => 'auto-retro',
            'technique' => 'auto-retro',
            'usage-collection' => 'auto-retro',
            'guide pratique' => 'auto-retro',
            'expérience de conduite' => 'auto-retro',
            'experience de conduite' => 'auto-retro',
            'auto retro' => 'auto-retro',
            'auto-rétro' => 'auto-retro',
            'vie locale' => 'vie-locale',
        ],
        'subcategories' => [
            'origines-chronologie' => 'histoire-automobile',
            'chronologie austin' => 'histoire-automobile',
            'industrie-longbridge' => 'histoire-automobile',
            'industrie automobile britannique' => 'histoire-automobile',
            'longbridge' => 'histoire-automobile',
            'berlines-populaires' => 'modeles-et-versions',
            'berline britannique' => 'modeles-et-versions',
            'voiture populaire' => 'modeles-et-versions',
            'sport-roadsters' => 'modeles-et-versions',
            'roadster anglais' => 'modeles-et-versions',
            'mecanique-entretien' => 'restauration-et-entretien',
            'entretien austin' => 'restauration-et-entretien',
            'mecanique anglaise' => 'restauration-et-entretien',
            'mécanique anglaise' => 'restauration-et-entretien',
            'restauration-pieces' => 'restauration-et-entretien',
            'restauration austin' => 'restauration-et-entretien',
            'pièces austin' => 'restauration-et-entretien',
            'pieces austin' => 'restauration-et-entretien',
            'conduite-balades' => 'conduite-et-collection',
            'balade en ancienne' => 'conduite-et-collection',
            'conduite ancienne' => 'conduite-et-collection',
            'achat-cote' => 'conduite-et-collection',
            'achat voiture ancienne' => 'conduite-et-collection',
            'cote austin' => 'conduite-et-collection',
            'prix voiture ancienne' => 'conduite-et-collection',
            'golfe de saint tropez' => 'golfe-saint-tropez',
            'villages et balades' => 'villages-et-balades',
            'evenements' => 'evenements-et-animations',
            'animations' => 'evenements-et-animations',
            'lieux et memoire' => 'lieux-et-memoire',
        ],
        'tags' => [
            'mini' => 'mini-austin',
            'Austin Mini' => 'mini-austin',
            'mini austin' => 'mini-austin',
            'A30' => 'austin',
            'Austin-Healey' => 'austin',
            'Austin Healey' => 'austin',
            'Donald Healey' => 'austin',
            'Austin Rover' => 'austin',
            'Austin A40 Farina' => 'austin',
            'Austin Cambridge' => 'austin',
            'Austin Seven' => 'austin',
            'austin-seven' => 'austin',
            'austin-a30' => 'austin',
            'austin-a40-farina' => 'austin',
            'austin-cambridge' => 'austin',
            'austin-healey' => 'austin',
            'herbert-austin' => 'austin',
            'austin-rover' => 'austin',
            'Citroën' => 'citroen',
            'mercedes-benz' => 'mercedes',
            'Golfe de Saint-Tropez' => 'golfe-saint-tropez',
            'golfe saint tropez' => 'golfe-saint-tropez',
            'saint tropez' => 'saint-tropez',
            'St Tropez' => 'saint-tropez',
            'auto rétro' => 'voiture-ancienne',
            'auto retro' => 'voiture-ancienne',
            'voiture d’avant-guerre' => 'histoire',
            'voiture d avant guerre' => 'histoire',
            'avant-guerre' => 'histoire',
            'Longbridge' => 'histoire',
            'longbridge' => 'histoire',
            'BMC' => 'histoire',
            'bmc' => 'histoire',
            'British Leyland' => 'histoire',
            'british-leyland' => 'histoire',
            'industrie automobile britannique' => 'histoire',
            'industrie britannique' => 'histoire',
            'industrie-britannique' => 'histoire',
            'crise industrielle' => 'histoire',
            'Morris' => 'voiture-anglaise',
            'morris' => 'voiture-anglaise',
            'MG' => 'voiture-anglaise',
            'mg' => 'voiture-anglaise',
            'roadster-anglais' => 'voiture-anglaise',
            'roadster anglais' => 'voiture-anglaise',
            'voiture anglaise ancienne' => 'voiture-anglaise',
            'moteur Austin' => 'mecanique',
            'moteur-a-series' => 'mecanique',
            'OHV' => 'mecanique',
            'fabrication automobile' => 'mecanique',
            'technique-automobile' => 'mecanique',
            'mecanique-anglaise' => 'mecanique',
            'mécanique anglaise' => 'mecanique',
            'entretien Austin' => 'entretien',
            'restauration Austin' => 'restauration',
            'pièces Austin' => 'restauration',
            'pieces Austin' => 'restauration',
            'pieces-detachees' => 'restauration',
            'Pininfarina' => 'carrosserie',
            'pininfarina' => 'carrosserie',
            'achat voiture ancienne' => 'collection',
            'collection Austin' => 'collection',
            'achat-collection' => 'collection',
            'prix voiture ancienne' => 'collection',
            'cote Austin' => 'collection',
            'prix-cote' => 'collection',
            'balade en ancienne' => 'route',
            'conduite-ancienne' => 'route',
            'chronologie Austin' => 'histoire',
            'Birmingham' => 'histoire',
            'birmingham' => 'histoire',
            'événement' => 'evenement',
            'evenements' => 'evenement',
            'événements' => 'evenement',
            'animation' => 'evenement',
        ],
    ],
];
